### ISSUE TITLE
Screen is not cleared on Ubuntu 19.10

### ISSUE THREAD

**Issue by atticus5** [Tyyppi77/imgui_sdl#11]
![Selection_001](https://user-images.githubusercontent.com/28069262/72680846-2c0a5900-3ac7-11ea-966d-ad6b6cc14b76.png)

**Comment by Tyyppi77** [comment]
What version of SDL do you use? There's a known issue about an SDL bug with window clearing, see #6.

**Comment by atticus5** [comment]
SDL 2.0.10, but I found this commit solves the issue [jesselawson@c37cb87](https://github.com/jesselawson/imgui_sdl/commit/c37cb8719b55d2c736c8977c377a42f76da3ad83)

I saw that someone said to wait for a fix from SDL 2.0.11, that means it works nice with older SDL versions?

**Comment by Tyyppi77** [comment]
I don't know if there's a version of SDL where this broke, or if all versions before 2.0.11 have this issue. SDL 2.0.11 should fix this missbehaviour of the clip rects.

**Comment by atticus5** [comment]
Anyway I will use that fix for now. I just want to thank you dearly for this implementation, my dream is to make my game with only the SDL_Renderer, being able to have imgui is a treat! I tip my hat to you sir!
