### ISSUE TITLE
Color pick wheel does not represent right

### ISSUE THREAD

**Issue by paladin-t** [Tyyppi77/imgui_sdl#16]
![image](https://user-images.githubusercontent.com/2062224/82022511-6378c300-96bf-11ea-8d02-e1a3ed250725.png)

The triangle is not colored, and there are notches on the wheel.

I'm using latest imgui_sdl and imgui v1.76

**Comment by Tyyppi77** [comment]
What platform are you on? What SDL version are you using?

The notches are 100% expected, as mentioned in the README the output of the triangle rasterizer is far from perfect. I'm unsure what's happening with the inner triangle, I'll see if I can find time to look into this.

**Comment by paladin-t** [comment]
its sdl v2.0.10, and both uncolored on win7/win10 64bit

**Comment by Tyyppi77** [comment]
There were a bunch of other rendering issues found with SDL2.0.10, could you try the newest version and see if that has an effect on this?

**Comment by paladin-t** [comment]
It remains in the latest SDL v2.0.12.
