### ISSUE TITLE
Custom image rendering seems to be broken again

### ISSUE THREAD

**Issue by Tyyppi77** [Tyyppi77/imgui_sdl#2]

**Comment by zovt** [comment]
Would love to help debug this! Currently blocking me on a project

**Comment by zovt** [comment]
From my investigation, it would seem that the `texture` variable is being set to an SDL_Texture* pointer somewhere instead of the ImGuiSDL Texture type. I'll look into it some more this week/end most likely

**Comment by Tyyppi77** [comment]
Yeah I apologize for my inactivity on fixing this, I've been busy with a bunch of other stuff.

I'll try to look into this too, I think I managed to fix this on some project of my own that was using an offline version of ImGuiSDL. If I recall correctly, this issue is indeed in a type clash between the ImGuiSDL Texture type and SDL_Texture type. I think the in-library texture is required for some optimizations, and there is probably some code that doesn't account for the fact that a user might pass a SDL_Texture* to the custom image drawing functionality.

**Comment by zovt** [comment]
No worries man, appreciate the existing work so far! Very useful

**Comment by Tyyppi77** [comment]
Fixed in https://github.com/Tyyppi77/imgui_sdl/commit/cc2372a01515b25ee09dd43e34565bb3f51e78d4. Please let me know if this fix works for you, if it doesn't, I'm happy to reopen and reinvestigate.

**Comment by zovt** [comment]
Looks good! Thank you man :+1:
