### ISSUE TITLE
The example program segfaults

### ISSUE THREAD

**Issue by RosenGeorgiev** [Tyyppi77/imgui_sdl#4]
SDL version: 2.0.9
ImGUI version: v.1.68
Compiler: gcc-4.8
Tested on Ubuntu 16.04 and OpenSuSE 42.1

Here is the backtrace:
\# 0  0x00007ffff7b2d7d3 in ?? () from /usr/lib64/libSDL2-2.0.so.0
\# 1  0x00000000004633a0 in (anonymous namespace)::DrawRectangle (bounding=..., texture=0x20aae00, color=..., 
    doHorizontalFlip=false, doVerticalFlip=false) at imgui_sdl.cpp:442
\# 2  0x0000000000463a49 in ImGuiSDL::Render (drawData=0x2064690) at imgui_sdl.cpp:555
\# 3  0x000000000040291f in main () at example.cpp:73

**Comment by Tyyppi77** [comment]
Related to https://github.com/Tyyppi77/imgui_sdl/issues/2, should be fixed in https://github.com/Tyyppi77/imgui_sdl/commit/cc2372a01515b25ee09dd43e34565bb3f51e78d4. Apologies for the delay.
