### ISSUE TITLE
SDL_Render state modified

### ISSUE THREAD

**Issue by JayFoxRox** [Tyyppi77/imgui_sdl#8]
imgui_sdl modifies some SDL state without resetting it. This seems to be a bug, as imgui_sdl *does* undo its changes to the SDL_Render blend-mode.

Things I've seen modified, but not reset before returning into user-code:

- `SDL_RenderSetClipRect` (region / state)
- `SDL_SetRenderTarget`
- `SDL_SetRenderDrawColor`
- Potentially `SDL_SetTextureColorMod` (I'm not sure if this affects user images)

*(There might be more)*

As SDL seems to do lazy updating (at least in some backends), changing these things back and forth shouldn't hurt. Therefore, I recommend implementing a fix (over just documenting it).

**Comment by Tyyppi77** [comment]
Great points, I hadn't considered saving those states. It's unlikely that I'll have the time to implement these changes, so I would very much welcome a PR with these states saved before rendering, and restored after the rendering pass.
